site_name: Bruno Ribeiro
site_url: https://brunojlle.github.io/

nav:
  - About me: 'index.md'
  - Code examples: 'projects/code-examples.md'
  - Content tabs: 'projects/content-tabs.md'
  - Admonitions: 'projects/admonitions.md'
  - Diagrama examples: 'projects/diagrama-examples.md'

theme:
  name: material
  # font:
  #   text: Merriweather Sans
  #   code: Red Hat Mono
  # icon:
  #   logo: fontawesome/solid/b
  # favicon: assets/cloud-intelligence.png
  features:
   - navigation.footer
  # palette:
  #   # Dark Mode
  #   - scheme: slate
  #     toggle:
  #       icon: material/weather-sunny
  #       name: Dark mode
  #     primary: green
  #     accent: deep purple

  #   # Light Mode
  #   - scheme: default
  #     toggle:
  #       icon: material/weather-night
  #       name: Light mode
  #     primary: blue
  #     accent: deep orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: simple/github
      link: https://github.com/brunojlle

    - icon: simple/linkedin
      link: https://www.linkedin.com/in/brunoribeiro7

copyright: Copyright &copy; 2024 Bruno Ribeiro